fc-list: /afs/ics.muni.cz/software/conda-modules/5.3.1/bin/../lib/./././libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /afs/ics.muni.cz/software/conda-modules/5.3.1/bin/../lib/././libicuuc.so.58)
fc-list: /afs/ics.muni.cz/software/conda-modules/5.3.1/bin/../lib/./././libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /afs/ics.muni.cz/software/conda-modules/5.3.1/bin/../lib/././libicuuc.so.58)
2022-02-17 14:48:58.050 | DEBUG    | __main__:<module>:27 - outputdir=/scratch/bohdany/job_10354220.meta-pbs.metacentrum.cz/data/processed
2022-02-17 14:48:58.050 | DEBUG    | __main__:<module>:28 - input_data_dir=/scratch/bohdany/job_10354220.meta-pbs.metacentrum.cz/data/orig
2022-02-17 14:48:58.050 | DEBUG    | __main__:<module>:30 - <generator object Path.glob at 0x14fe5a887308>
2022-02-17 14:48:58.257 | DEBUG    | __main__:<module>:45 - /scratch/bohdany/job_10354220.meta-pbs.metacentrum.cz/data/orig/data/images/13.jpg
2022-02-17 14:48:58.259 | DEBUG    | __main__:<module>:47 - /scratch/bohdany/job_10354220.meta-pbs.metacentrum.cz/data/processed/vis_train/13.jpg
2022-02-17 14:48:58.451 | DEBUG    | __main__:<module>:45 - /scratch/bohdany/job_10354220.meta-pbs.metacentrum.cz/data/orig/data/images/1.jpg
2022-02-17 14:48:58.452 | DEBUG    | __main__:<module>:47 - /scratch/bohdany/job_10354220.meta-pbs.metacentrum.cz/data/processed/vis_train/1.jpg
2022-02-17 14:48:58.615 | DEBUG    | __main__:<module>:45 - /scratch/bohdany/job_10354220.meta-pbs.metacentrum.cz/data/orig/data/images/10.jpg
2022-02-17 14:48:58.616 | DEBUG    | __main__:<module>:47 - /scratch/bohdany/job_10354220.meta-pbs.metacentrum.cz/data/processed/vis_train/10.jpg
Traceback (most recent call last):
  File "/storage/plzen1/home/bohdany/projects/tutorials/metacentrum/detectron2_quickstart/detectron2_custom_coco_data_segmentation.py", line 58, in <module>
    cfg.merge_from_file(f"/storage/plzen1/home/{logname}/projects/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  File "/auto/vestec1-elixir/home/bohdany/detectron2/detectron2/config/config.py", line 30, in merge_from_file
    assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
AssertionError: Config file '/storage/plzen1/home/bohdany/projects/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml' does not exist!
